notifications:
  email: false

dist: trusty

sudo: required

language: python

python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
  - "pypy"
  - "pypy3"

addons: {apt: {packages: [xsel]}}

deploy:
  true:
    branch: master
  distributions: sdist bdist_wheel
  user: mandeepb
  provider: pypi
  edge:
    branch: v1.8.45
  password:
    secure: qqawdrJXlyPcnPiB08h5GFVZrnw46fTwk9n7EDYxoY9fLHTsc0QxkaLRVhMyuT6SxUw97uncOlGHCwbgAWFa7OYhUMUwA3+YqeKOfsSlSmwKR7CRDlqZzmk7kMhzbdSutNGQ7/M8zplQAfQIAdeT3kBdkiuFlfvO5NcfdSAZf/nGOSIsFEPUUMGn9p1l04BAGw4wqnqu9NVnI7eXVaAIHedlzD31gSv5DgXAUMP7TYZ/SFim3dz7QxD5PqJ6ylfPCgw9mNVqB5orbwaDBK49ZNT7ZuPv3Lmr6MsK3s8PzVMP9QTlfhOC3obOb1jsBWWBG/ZwQg2necAQFVOTxWPdijQl5lm7yKN3Af+bf8oVKXJre/KzAwtK8yV9Z0H8EHxeyU7ZXJQH613BnjXkxct+bANETN0X/fA0sHO082kv1t/syeQIqAyq2l2gd262/YiFwYQkBhN+6ZQq8fDll517VpS+JW+JqjqycVKeM2w/w7iWrurI0ruXltvaZDoFI/PeOPVFZyrcdF1gkNx8xn09uOYlpuuIZfGIWzQnszmu43YycTEAW30sGmAPd4tpXHtF1UbfKAec7HUgcCqQ3Q/QUDEKauZ69E++M7UHSj6ZJ/pjBIzlMfVZgPHuxNJcqW/ocQMwppdh3oKMuoxXvX3hFAFG8clloQbftDxnbR2giuE=


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install cryptography
  - pip install coveralls
  - pip install coverage
  - pip install pytest
  - pip install pytest-cov
  - pip install six
  - python setup.py install

script:
  - pytest -v --cov=.

after_success:
  - coveralls
